server:
  port: 8080

spring:

  data:
    mongodb:
      uri: mongodb+srv://jlsicsu:JLSB250887@mongobufallo.inmdmeu.mongodb.net/paneladev

  mail:
    host: smtp.gmail.com
    port: 587
    username: jlsicsu@gmail.com
    password: zlngyyeuazuqxqix
    properties:
      mail:
        smtp:
          auth: true
          secure: ssl
          starttls:
            enabled: true
            required: true

feature-toggle:
  resendEmail: true